 # These are supported funding model platforms

github: webjetclouds-agency # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: webjetclouds # Replace with a single Patreon username
#open_collective: # Replace with a single Open Collective username
ko_fi: webjetclouds # Replace with a single Ko-fi username
liberapay: webjetclouds # Replace with a single Liberapay username
issuehunt: webjetclouds # Replace with a single IssueHunt username
polar: webjetclouds # Replace with a single Polar username
buy_me_a_coffee: webjetclouds # Replace with a single Buy Me a Coffee username
thanks_dev: webjetclouds-agency # Replace with up to 4 Thanks.dev usernames e.g., [user1, user2]
custom: https://funding.webjet.cloud/donations/wp-opensource-php/ # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
